services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: headkey
      POSTGRES_PASSWORD: headkey
      POSTGRES_DB: headkey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
