services:
  postgres:
    profiles: ["postgres"]
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: headkey
      POSTGRES_PASSWORD: headkey
      POSTGRES_DB: headkey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./persistence-postgres/src/main/resources/sql/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql
  
  elasticsearch:
    profiles: ["elasticsearch"]
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8000
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    
  elasticvue:
    profiles: ["elasticsearch"]
    image: cars10/elasticvue
    ports:
      - "8000:8080"
    environment:
      ELASTICVUE_CLUSTERS: '[{"name": "cluster", "uri": "http://localhost:9200"}]'
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  elasticsearch_data:
